### ISSUE TITLE
Head of organisation user stories

### ISSUE THREAD

**Issue by RhodesPeter** [FAC9/ux-ui-project#2]
**User:** 

Head of organisation / administrator 

**Story:** 

- [ ] As the head of the organisation,
       I want to be able to reduce administration time,
       so that I can do my job quicker.

- [ ] As the head of the organisation,
       I want to remind the trainee chefs that they need to pay,
       so that I get the payments on time.

- [ ] As the head of the organisation,
       I want to see visualised data of all of the trainee chefs' payments,
       so that I can understand my business better.

- [ ] As the head of the organisation,
       I want to see visualised data of individual trainee chef's payments,
       so that I can help them keep on track.

- [ ] As the head of the organisation,
       I want to print/export/download spreadsheets of the data on trainee chef payments,
       so that I can pass these onto my admin team.

- [ ] As the head of the organisation,
       I want to directly message the trainee chefs,
       so that I can help them make their payments.

**Comment by denesnori** [comment]
We have been advised to turn these into individual issues so that they can be referenced with their own unique issue number.
