### ISSUE TITLE
Number, date, currency formats

### ISSUE THREAD

**Issue by emilyb7** [FAC9/ux-ui-project#40]
At https://github.com/FAC9/ux-ui-project/blob/master/public/index.html

The £ sign should probably be outside of the input field, so that it doesn't disappear when the user stops typing

Large numbers should be separated by commas (this may just be a preference, but it's definitely more common)

Date format in UK is most commonly dd/mm/yy or dd/mm/yyyy - using dots is not all that common

Also, while I'm being picky, "Log out" should be 2 words

**Comment by lucymonie** [comment]
Thanks @emilyb7. 
- I have fixed the pound sign and the date separators.
- Thanks for the note about the numbers. We don't go for commas in big numbers, so have left this one.
- This is a British app, and the date doesn't begin with the year, so I think it's safe to assume people will know that it's day then month.
- It's a style decision on 'log out' vs 'logout'. I think we'll stick with the latter, but thanks for the note.
