### ISSUE TITLE
@keyframes blinker

### ISSUE THREAD

**Issue by stevehopkinson** [FAC9/ux-ui-project#43]
Please no

**Comment by Jwhiles** [comment]
alternately, try changing the animation to something like this

```
@keyframes blinker {
  50% { opacity: 0; }
  100% { opacity: 1; }
}
```

this makes the repetition of the animation less jarring :)

**Comment by Jwhiles** [comment]
or to make it more jarring
```
@keyframes blinker {
  50% {
    opacity: 0;
    transform: rotate(50deg);
   }
  100% {
    opacity: 1;
    transform: rotate(0deg);
  }
}
```

**Comment by marisid** [comment]
I agree that the blinking animation is a bit distracting.

**Comment by lucymonie** [comment]
I did it just to make your eyeballs hurt. Love you all.

And thanks for taking it to the next level @Jwhiles.
