### ISSUE TITLE
Chart is illegibly tiny; labels aren't displaying in full

### ISSUE THREAD

**Issue by stevehopkinson** [FAC9/ux-ui-project#49]
![screen shot 2016-12-21 at 10 52 34](https://cloud.githubusercontent.com/assets/5929394/21386874/d481acc2-c76c-11e6-8995-dc11158cfb41.png)

**Comment by emilyb7** [comment]
I would add to this, that it's not immediately clear what the £3,000 that stuck onto the left hand side of the chart refers to...

**Comment by lucymonie** [comment]
The £3000 is the total the users have to pay back, so I think it would be clear to them. Will try to make it bigger.
