### ISSUE TITLE
Labels on login form

### ISSUE THREAD

**Issue by emilyb7** [FAC9/ux-ui-project#52]
The labels for the login form are in a separate div container from the input fields to which they belong. I imagine that this is bad for screen readers.

**Comment by emilyb7** [comment]
Actually, that may be completely wrong. But anyway, I was a bit confused by the layout.

**Comment by denesnori** [comment]
The login page has proper desktop and mobile view options. And we need the seperate divs to design the desktop layout. I only added them when I made the desktop version :D
But yes, we suffer from severe divitis... ^^
