### ISSUE TITLE
'Need help' tab poking out from behind 'hungry unicorns' tab

### ISSUE THREAD

**Issue by stevehopkinson** [FAC9/ux-ui-project#55]
Looks… unusual.

![screen shot 2016-12-21 at 10 53 31](https://cloud.githubusercontent.com/assets/5929394/21387062/d4494d4a-c76d-11e6-8732-8d0b1ebea9b6.png)

**Comment by lucymonie** [comment]
Thanks @stevehopkinson! You say the nicest things. That's a compliment, right...?
