### ISSUE TITLE
Improvements on the 'need help' pop-up window

### ISSUE THREAD

**Issue by marisid** [FAC9/ux-ui-project#58]
- Start chatting button to be renamed to 'send your message' or 'get in touch' as there is no live chat room. Also, move it a bit higher up so that the user doesn't need to scroll down
- Message text `input` element to be changed to a `textarea` element so that the user can type multiline text and maybe change text alignment to top (I think this is done by default when you switch to `textarea`)?
- Link the need help pop-up window with the "Get in touch" section in the main user page (there is currently no way for the user to get in touch through that page).

**Comment by RhodesPeter** [comment]
Fixed with commit 324e395fe8b7eb626c401cdf155e39a6deb4fcf8
